export default {
  _930: "9:30 Club",
  theanthem: "The Anthem",
  blackcat: "Black Cat",
  citywinery: "City Winery",
  dc9: "DC9 Nightclub",
  echostage: "Echo Stage",
  thehamilton: "The Hamilton",
  howardtheatre: "The Howard Theatre",
  pieshop: "Pie Shop",
  pearlstreet: "Pearl Street",
  songbyrd: "Songbyrd Cafe",
  ustreet: "U Street Music Hall",
  unionstage: "Union Stage",
  velvetlounge: "The Velvet Lounge",
}
